content:
  source:
    git:
      branch:
        fallback: master
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift/cluster-ingress-operator.git
from:
  builder:
  - stream: golang
  member: openshift-enterprise-base
name: openshift/ose-cluster-ingress-operator
owners:
- dev@lists.openshift.redhat.com
- aos-network-edge@redhat.com
required: true
