content:
  source:
    dockerfile: Dockerfile.rhel7
    git:
      branch:
        fallback: master
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift/cluster-config-operator.git
from:
  builder:
  - stream: golang
  member: openshift-enterprise-base
name: openshift/ose-cluster-config-operator
owners:
- aos-master@redhat.com
- tnozicka@redhat.com
